server:
  port: 8089
  servlet:
    context-path: /api/cheer
    encoding:
      charset: utf-8
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka:8761/eureka

logging:
  level:
    org:
      jsoup: trace

spring:
  application:
    name: cheer

  datasource:
    # local 브랜치 용
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/backtoback?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: ssafy

    # develop 브랜치 용
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://k8a708.p.ssafy.io:3306/backtoback?useUnicode=true&characterEncoding=utf-8
    username: btob
    password: backback

    #추가
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true

  output.ansi.enabled: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none # create, update, none
    generate-ddl: false
    properties:
      hibernate:
        #        dialect:
        #        default_schema:
        format_sql: true
    defer-datasource-initialization: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul

  mvc:
    log-request-details: true # request의 parameter 값 등을 log에서 못 보는 설정 해제

  redis:
    host: localhost
    port: 6379


logging.level:
  #  org.apache: trace
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  org:
    springframework:

      security: trace

      boot:
        autoconfigure:
          security: trace
      web: trace

      http: trace